apiVersion: mycodexvantaos.io/v1
kind: FoundationReference-architecture
metadata:
  name: mycodexvantaos-algorithm-foundation-reference-architecture
  version: 1.0.0
  foundation: mycodexvantaos-algorithm-foundation
  date: "2026-06-29"
  status: active
