!!python/object/apply:collections.OrderedDict
- - - global
    - !!python/object/apply:collections.OrderedDict
      - - - imageTag
          - latest
        - - platform
          - mycodexvantaos
  - - services
    - !!python/object/apply:collections.OrderedDict
      - - - mycodexvantaos-core-kernel
          - !!python/object/apply:collections.OrderedDict
            - - - replicas
                - 2
        - - mycodexvantaos-ai-embedding
          - !!python/object/apply:collections.OrderedDict
            - - - replicas
                - 2
        - - mycodexvantaos-ai-llm
          - !!python/object/apply:collections.OrderedDict
            - - - replicas
                - 2
