!!python/object/apply:collections.OrderedDict
- - - global
    - !!python/object/apply:collections.OrderedDict
      - - - runtimeMode
          - connected
        - - deploymentTarget
          - kubernetes
        - - platform
          - mycodexvantaos
