!!python/object/apply:collections.OrderedDict
- - - apiVersion
    - mycodexvantaos.org/v1
  - - kind
    - Provider
  - - metadata
    - !!python/object/apply:collections.OrderedDict
      - - - name
          - mycodexvantaos-deploy-argocd
        - - capability
          - deploy
        - - labels
          - !!python/object/apply:collections.OrderedDict
            - - - mycodexvantaos.org/managed-by
                - naming-spec-v1
              - - mycodexvantaos.org/specRef
                - '8.1'
  - - spec
    - !!python/object/apply:collections.OrderedDict
      - - - providerName
          - argocd
        - - isNative
          - false
        - - lifecycle
          - !!python/object/apply:collections.OrderedDict
            - - - stage
                - stable
        - - envVarPrefix
          - MYCODEXVANTAOS_DEPLOY
        - - configSchemaRef
          - ./config.schema.json
        - - description
          - Argo CD GitOps deployment provider.
  - - provider-id
    - mycodexvantaos-deploy-argocd
  - - capability
    - deploy
