apiVersion: mycodexvantaos.io/v1
kind: CloudEventsProfile
metadata:
  name: cloudevents-profile
spec:
  specVersion: '1.0'
  sourcePattern: 'mycodexvantaos://service/{service-id}'
  typePattern: 'io.mycodexvantaos.{domain}.{event-type}.{version}'
