---
extends: default
rules:
  document-start: disable
  line-length:
    max: 200
    allow-non-breakable-inline-mappings: true
  indentation: disable
  truthy:
    allowed-values: ["true", "false"]
    check-keys: true
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
ignore: |
  infra/helm/
  argocd/
  pnpm-lock.yaml
