apiVersion: v1
kind: ConfigMap
metadata:
  name: mycodexvantaos-ai-memory
  labels:
    app.kubernetes.io/name: mycodexvantaos-ai-memory
data:
  MYCODEXVANTAOS_MYCODEXVANTAOS_AI_MEMORY_LOG_LEVEL: info
  MYCODEXVANTAOS_MYCODEXVANTAOS_AI_MEMORY_PORT: '3000'
