name: Helm Chart Testing
"on":
  pull_request:
    paths:
    - deploy/helm/**
    - .config/helm/ct.yaml
permissions:
  contents: read
jobs:
  lint-test:
    name: Lint and Test Charts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
    - name: Set up Helm
      uses: azure/setup-helm@89f243019808d661448f86f3438f78553ae8e4a9
      with:
        version: v3.13.1
    - name: Set up chart-testing
      uses: helm/chart-testing-action@b12271825a072b4f98108643033f6a27e7f123c5
    - name: Run chart-testing (lint)
      run: ct lint --all --config .config/helm/ct.yaml
    - name: Create kind cluster
      uses: helm/kind-action@a63f7386c9e99a164b387e651e73b22410a563f3
    - name: Run chart-testing (install)
      run: ct install --all --config .config/helm/ct.yaml
