name: OpenAPI Linting
true:
  pull_request:
    paths:
    - apps/my-app/repo/contracts/openapi.yaml
    - .config/openapi/spectral.yaml
permissions:
  contents: read
jobs:
  spectral-lint:
    name: Spectral Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Run Spectral Lint
      uses: stoplightio/spectral-action@v1.0.0
      with:
        file_glob: apps/my-app/repo/contracts/openapi.yaml
        spectral_ruleset: .config/openapi/spectral.yaml
