name: Generate Provenance Attestation
true:
  release:
    types:
    - published
permissions:
  contents: read
  id-token: write
  actions: read
jobs:
  generate-provenance:
    name: Generate SLSA Provenance
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Download all artifacts
      uses: actions/download-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        path: artifacts
    - name: Generate SLSA Provenance
      uses: slsa-framework/slsa-github-generator@v1.9.0
      with:
        base64-subject: $(base64 -w0 artifacts/my-app-api/my-app-api)
        provenance-name: my-app-api.provenance
        upload-assets: true
