#!/usr/bin/env npx tsx
/**
 * @module tools/generators/generate-service
 * @description Scaffolds a new service in the platform.
 *
 * Generates:
 *   1. contracts/service-definitions/{service}.yaml
 *   2. packages/application/{service}/ (service class + index + barrel)
 *   3. Routes in apps/api-worker/index.ts (to be added manually)
 *
 * Usage:
 *   npx tsx tools/generators/generate-service.ts <service-name> <category>
 *
 * Example:
 *   npx tsx tools/generators/generate-service.ts billing automation
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "../..");

const VALID_CATEGORIES = [
  "knowledge",
  "agent",
  "workspace",
  "developer",
  "security",
  "storage",
  "model",
  "automation",
];

// ── Parse Args ──────────────────────────────────────────────────────────

const args = process.argv.slice(2);

if (args.length < 2) {
  console.error("Usage: npx tsx tools/generators/generate-service.ts <service-name> <category>");
  console.error(`Categories: ${VALID_CATEGORIES.join(", ")}`);
  process.exit(1);
}

const serviceName = args[0].toLowerCase().replace(/[^a-z0-9-]/g, "-");
const category = args[1].toLowerCase();

if (!VALID_CATEGORIES.includes(category)) {
  console.error(`Invalid category: ${category}`);
  console.error(`Valid categories: ${VALID_CATEGORIES.join(", ")}`);
  process.exit(1);
}

const pascalName = serviceName
  .split("-")
  .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
  .join("");
const className = `${pascalName}Service`;

console.log(`🚀 Generating service: ${serviceName} (${className}) in category: ${category}\n`);

// ── 1. Service Definition YAML ─────────────────────────────────────────

const serviceDefDir = path.join(ROOT, "contracts/service-definitions");
const serviceDefPath = path.join(serviceDefDir, `${serviceName}.yaml`);

if (fs.existsSync(serviceDefPath)) {
  console.error(`❌ Service definition already exists: ${serviceDefPath}`);
  process.exit(1);
}

const serviceDefContent = `# ${className} Service Definition
# Category: ${category}
# Generated by tools/generators/generate-service.ts

apiVersion: v1
kind: ServiceDefinition
metadata:
  name: ${serviceName}
  category: ${category}
  description: "${pascalName} service for the MyCodeXvantaOS platform"
  urnPrefix: "urn:mycodexvantaos:${category}:${serviceName}"

spec:
  capabilities: []
  # - name: ""
  #   description: ""
  #   inputs: []
  #   outputs: []

  dependencies: []
  # - service: ""
  #   capability: ""

  policies:
    - "platform-admin: full access"
    - "workspace-owner: manage within workspace"
    - "workspace-member: read within workspace"
    - "workspace-viewer: read metadata only"

  events:
    produced: []
    # - type: "com.mycodexvantaos.${serviceName}.created"
    consumed: []
    # - type: "com.mycodexvantaos.audit.event"

  resources: []
  # - kind: "${serviceName}-config"
  #   urnTemplate: "urn:mycodexvantaos:${category}:${serviceName}-config:{id}"
`;

fs.mkdirSync(serviceDefDir, { recursive: true });
fs.writeFileSync(serviceDefPath, serviceDefContent);
console.log(`✅ Created: contracts/service-definitions/${serviceName}.yaml`);

// ── 2. Application Service Package ─────────────────────────────────────

const appDir = path.join(ROOT, "packages/application", serviceName);

if (fs.existsSync(appDir)) {
  console.error(`❌ Application package already exists: ${appDir}`);
} else {
  fs.mkdirSync(appDir, { recursive: true });

  // Service class
  const serviceClassContent = `/**
 * @module packages/application/${serviceName}
 * @description ${className} — ${category} category service.
 *
 * TODO: Implement service methods.
 */

export class ${className} {
  constructor(
    // TODO: Inject required ports via constructor
  ) {}

  /**
   * TODO: Define service methods that map to capabilities
   * in contracts/service-definitions/${serviceName}.yaml
   */
}
`;

  fs.writeFileSync(path.join(appDir, `${serviceName}-service.ts`), serviceClassContent);
  console.log(`✅ Created: packages/application/${serviceName}/${serviceName}-service.ts`);

  // Index barrel
  const indexContent = `export { ${className} } from './${serviceName}-service.js';
`;

  fs.writeFileSync(path.join(appDir, "index.ts"), indexContent);
  console.log(`✅ Created: packages/application/${serviceName}/index.ts`);
}

// ── 3. Summary ─────────────────────────────────────────────────────────

console.log(`\n${"─".repeat(50)}`);
console.log("Service scaffolded! Next steps:");
console.log("");
console.log(`1. Edit contracts/service-definitions/${serviceName}.yaml`);
console.log(`2. Implement packages/application/${serviceName}/${serviceName}-service.ts`);
console.log(`3. Add routes to apps/api-worker/index.ts`);
console.log(`4. Add event types to contracts/events/events.yaml`);
console.log(`5. Add database tables to migrations/ (if needed)`);
console.log(`6. Update packages/application/index.ts barrel re-export`);
