import { NextResponse } from "next/server";

export const dynamic = "force-static";

// MyCodeXvantaOS Admin Dashboard - Inference Models API
// Lists all registered LM models and their status

const models = [
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "openai",
    status: "active",
    version: "2024-05-13",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputPrice: 5.0,
    outputPrice: 15.0,
    avgLatency: 180,
    totalRequests: 524000,
    errorRate: 0.002,
    endpoint: "https://api.openai.com/v1/chat/completions",
    lastUsed: new Date().toISOString(),
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "openai",
    status: "active",
    version: "2024-07-18",
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputPrice: 0.15,
    outputPrice: 0.6,
    avgLatency: 95,
    totalRequests: 312000,
    errorRate: 0.001,
    endpoint: "https://api.openai.com/v1/chat/completions",
    lastUsed: new Date().toISOString(),
  },
  {
    id: "claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "anthropic",
    status: "active",
    version: "2024-06-20",
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputPrice: 3.0,
    outputPrice: 15.0,
    avgLatency: 165,
    totalRequests: 287000,
    errorRate: 0.003,
    endpoint: "https://api.anthropic.com/v1/messages",
    lastUsed: new Date().toISOString(),
  },
  {
    id: "claude-3-haiku",
    name: "Claude 3 Haiku",
    provider: "anthropic",
    status: "active",
    version: "2024-03-13",
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputPrice: 0.25,
    outputPrice: 1.25,
    avgLatency: 72,
    totalRequests: 198000,
    errorRate: 0.001,
    endpoint: "https://api.anthropic.com/v1/messages",
    lastUsed: new Date().toISOString(),
  },
  {
    id: "gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    provider: "google",
    status: "active",
    version: "2024-05-01",
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    inputPrice: 1.25,
    outputPrice: 5.0,
    avgLatency: 220,
    totalRequests: 156000,
    errorRate: 0.004,
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models",
    lastUsed: new Date().toISOString(),
  },
  {
    id: "gemini-1.5-flash",
    name: "Gemini 1.5 Flash",
    provider: "google",
    status: "active",
    version: "2024-05-01",
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    inputPrice: 0.075,
    outputPrice: 0.3,
    avgLatency: 55,
    totalRequests: 421000,
    errorRate: 0.002,
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models",
    lastUsed: new Date().toISOString(),
  },
  {
    id: "llama-3.1-70b",
    name: "Llama 3.1 70B",
    provider: "meta",
    status: "active",
    version: "2024-07-23",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputPrice: 0.0,
    outputPrice: 0.0,
    avgLatency: 130,
    totalRequests: 89000,
    errorRate: 0.005,
    endpoint: "https://inference.internal.mycodevantaos.io/v1/chat/completions",
    lastUsed: new Date().toISOString(),
  },
  {
    id: "mistral-large",
    name: "Mistral Large",
    provider: "mistral",
    status: "idle",
    version: "2024-07-23",
    contextWindow: 32000,
    maxOutputTokens: 4096,
    inputPrice: 2.0,
    outputPrice: 6.0,
    avgLatency: 145,
    totalRequests: 34000,
    errorRate: 0.006,
    endpoint: "https://api.mistral.ai/v1/chat/completions",
    lastUsed: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "command-r-plus",
    name: "Command R+",
    provider: "cohere",
    status: "idle",
    version: "2024-06-01",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputPrice: 2.5,
    outputPrice: 10.0,
    avgLatency: 200,
    totalRequests: 12000,
    errorRate: 0.008,
    endpoint: "https://api.cohere.ai/v1/chat",
    lastUsed: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: "qwen-2-72b",
    name: "Qwen 2 72B",
    provider: "alibaba",
    status: "offline",
    version: "2024-06-01",
    contextWindow: 32000,
    maxOutputTokens: 4096,
    inputPrice: 0.0,
    outputPrice: 0.0,
    avgLatency: 0,
    totalRequests: 0,
    errorRate: 0,
    endpoint: "https://inference.internal.mycodevantaos.io/v1/chat/completions",
    lastUsed: null,
  },
];

export async function GET() {
  return NextResponse.json({
    models,
    total: models.length,
    active: models.filter((m) => m.status === "active").length,
    idle: models.filter((m) => m.status === "idle").length,
    offline: models.filter((m) => m.status === "offline").length,
  });
}
