name: Dependency Review

on:
  pull_request:
    branches: ['main']

concurrency:
  group: dep-review-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@4901385134134e04cec5fbe5ddfe3b2c5bd5d976
        with:
          config-file: .github/dependency-review-config.yml
